BOWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BOWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            //ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            //ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BOWeb/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOWeb.Classes;

// thank you http://stackoverflow.com/questions/12378445/asp-net-mvc-3-password-protect-view
namespace BOWeb.Controllers
{

    public class ToolsController : Controller
    {
        [SimpleMembership]
        public ActionResult Index()
        {
            return View();
        }

        [SimpleMembership]
        public ActionResult CheckTKCurrency()
        {
            return View();
        }

        [SimpleMembership]
        public ActionResult CreateOneTimeScore()
        {
            return View();
        }

        [SimpleMembership]
        public ActionResult ExportResumes()
        {
            return View();
        }


        //[SimpleMembership]
        [HttpGet]
        public ActionResult SignIn()
        {
            return View();
        }

        //[SimpleMembership]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult SignIn(BOWeb.Models.SignIn SignIn)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session["myApp-Authentication"] = SignIn.Password;
                //string redirectOnSuccess = HttpContext.Request.Url.AbsolutePath;
                if (SignIn.Password == "bingobangobongo")
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }


        [SimpleMembership]
        [HttpGet]
        public ActionResult ResetCandidatePassword()
        {
            return View();
        }

        [SimpleMembership]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult ResetCandidatePassword(BOWeb.Models.Candidate Candidate)
        {
            if (ModelState.IsValid)
            {
                Utilities u = new Utilities();
                u.UpdateCandidatePassword(Candidate); //(Candidate.Candidate_Id, Candidate.Password);
                ViewBag.StatusMessage = "Password reset successfully!";
            }
            else
            {
                ViewBag.StatusMessage = "There was a problem with your input data.";
            }
            return View();
        }

        [SimpleMembership]
        [HttpGet]
        public ActionResult ChangeConnections()
        {
            return View();
        }

        [SimpleMembership]
        public ActionResult ChangeConnections(BOWeb.Models.BackOfficeConnections BOConnections)
        {
            Utilities u = new Utilities();
            u.SaveBackOfficeConnections(BOConnections);
            return View();
        }

        [SimpleMembership]
        public ActionResult UploadJobBoardImage()
        {
            return View();
        }
    }
}

BOWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>Job Market Maker - Back Office</h2>

<p>This site is for Job Market Maker's various back-office tools that fall outside of the main product.</p>

BOWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BOWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>Settings</h2>
<ul>
    <li>@Html.ActionLink("Change connections", "ChangeConnections", "Tools")</li>
</ul>

<h2>General Tools</h2>
<ul>
    <li>@Html.ActionLink("Export resumes", "ExportResumes", "Tools")</li>
    <li>@Html.ActionLink("Upload a Job Board Image", "UploadJobBoardImage", "Tools")</li>
    <li>@Html.ActionLink("Reset a Candidate Password", "ResetCandidatePassword", "Tools")</li>
</ul>

<h2>TextKernel Tools</h2>
<ul>
    <li>@Html.ActionLink("Check TK Currency", "CheckTKCurrency", "Tools")</li>
    <li>@Html.ActionLink("Create a one-time Candidate + Job Opening score", "CreateOneTimeScore", "Tools")</li>
</ul>

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@